# Generated by Django 4.1.4 on 2023-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavemanagement",
            name="leave_requested_for",
            field=models.CharField(
                choices=[
                    ("F", "Full day"),
                    ("FH", "First half"),
                    ("SH", "Second half"),
                ],
                default="F",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="full_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payslip",
            name="half_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payslip",
            name="leave_taken",
            field=models.IntegerField(default=0),
        ),
    ]
